# See https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
---
_extends: .github
tag-template: open-mfa-$NEXT_MINOR_VERSION
template: |
  ## Releases

  ### 🚀 New Features
  - Feature summaries here

  ### 🛠 Fixes
  - Fixed issues here
